In [12]:
import numpy as np

employees = np.array([
    [25, 50000],
    [30, 60000],
    [35, 70000],
    [40, 80000]
])

employees[:, 0]

salaries = employees[:, 1]


print(type(salaries))


<class 'numpy.ndarray'>


In [13]:
import numpy as np

employees = np.array([
    [25, 50000],
    [30, 60000],
    [35, 70000],
    [40, 80000]
])

employees[1:3]

array([[   30, 60000],
       [   35, 70000]])

In [16]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50, 60, 70, 80])
numbers[:4]
numbers[4:]
numbers[-3:]

array([60, 70, 80])

In [ ]:
# Broadcasting:

import numpy as np

matrix = np.array([
    [10,20,30],
    [40,50,60],
])

adjustment = np.array([1,2,3])

matrix + adjustment



array([[11, 22, 33],
       [41, 52, 63]])

In [22]:
# Reshaping rule : rows * columns = total number of elements

arr = np.array([1,2,3,4,5,6,7,8]) 

arr.reshape(2,4) # woks
arr.reshape(4,2) # works
arr.reshape(8,1) # works
#arr.reshape(2,3) # does not work

#Useful NumPy Shortcut

#You don't always have to specify both dimensions.

arr.reshape(2, -1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
import numpy as np

scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95],
    [50, 65, 70]
])

scores.shape
scores.max()
scores.min()

np.int64(50)

In [7]:
import numpy as np

scores = np.array([70, 85, 90, 65, 95])

scores_mean = scores.mean()
print("Mean score:", scores_mean)

scores_max = scores.max()
print("Maximum score:", scores_max)

scores_min = scores.min()
print("Minimum score:", scores_min)

scores_incr_10 = scores +10
print("Scores increased by 10:", scores_incr_10)

scores_find_middle_3 = scores[1:4]
print("Middle three scores:", scores_find_middle_3)

Mean score: 81.0
Maximum score: 95
Minimum score: 65
Scores increased by 10: [ 80  95 100  75 105]
Middle three scores: [85 90 65]


In [3]:
import numpy as np

arr = np.array([20,25,30,35,40])

print(arr) 
print(type(arr)) # Output: 20

[20 25 30 35 40]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)

modules = [
    "Login",
    "Checkout",
    "Payments",
    "Search",
    "Profile",
    "Orders"
]

environments = [
    "QA",
    "UAT",
    "PROD"
]

results = [
    "Pass",
    "Fail"
]

failure_categories = [
    "Element Missing",
    "Timeout",
    "Assertion Failure",
    "Environment Issue",
    "None"
]

n = 1000

df = pd.DataFrame({
    "Test_ID": np.arange(1, n + 1),

    "Module": np.random.choice(modules, size=n),

    "Environment": np.random.choice(
        environments,
        size=n,
        p=[0.5, 0.3, 0.2]
    ),

    "Execution_Time": np.random.randint(
        5,
        60,
        size=n
    ),

    "Result": np.random.choice(
        results,
        size=n,
        p=[0.85, 0.15]
    )
})

df["Failure_Category"] = np.where(
    df["Result"] == "Fail",
    np.random.choice(
        failure_categories[:-1],
        size=n
    ),
    "None"
)

df["Run_Date"] = pd.date_range(
    start="2026-01-01",
    periods=n,
    freq="H"
)


,Test_ID,Module,Environment,Execution_Time,Result,Failure_Category,Run_Date
0,1,Search,QA,26,Pass,None,2026-01-01 00:00:00
1,2,Profile,QA,41,Pass,None,2026-01-01 01:00:00
2,3,Payments,QA,56,Pass,None,2026-01-01 02:00:00
3,4,Profile,QA,46,Pass,None,2026-01-01 03:00:00
4,5,Profile,QA,16,Pass,None,2026-01-01 04:00:00
